apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  envs:
  - environment-values.env
  name: new-single-inrepo-port-ingress-noautodeploy-environment-values
- behavior: merge
  envs:
  - container.env
  name: new-single-inrepo-port-ingress-noautodeploy-container-vars
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/version: ""
namespace: dev
resources:
- ../../base
images:
- name: ghcr.io/fake-org/fake-registry/new-single-inrepo-port-ingress-noautodeploy
